travis:
  secure:
    BINSTAR_TOKEN: 3w1t98G4v7YhHjHTPmbU7MUtLLc5Lm3reFlgaabB59TfQzJZ9Wh/B6dYvGcKFXTkd3w+JzZhTAv/tZvqS7YK5RkaLf0PyKCfNROdsMyWkH+Bere1nu8jD+pZyxNKd02TuxlWseQAMJhMPe0que1G6uyFD/sl6DjGGovBVGZ8BlePOOZPzixs+R/3+H4KVS9RYKJftnoFLnHqr7NghXT9qL7ptjg+GhRWN5FgCjGUmm48l1Nmz91f0A+4J61uCwq5rHQtElu4gz7OVEmDiPjhgwCEwPtPuRPsuO5zi91DUGQZ0A297VuewTksZLtirPsgI1hxc01wW9/QF5G4LV1aB5rcfAL2r5wyuyL/bqkPskwAAOz7QVbRUzJ5LMnWPNmk5bwptUrM/KU2hMOEMsn916g62gecOPWZ4TS4m0H57vXcfMhk8YbqTcLjPDLuOkiBuqjDFYnT2u59hEGSBjcC8cyTQKn9Uc1w9mQH8ewGg2ILTVIxX+saIdS5IPnZKYW9g18uagdN/vPNsHm+zpcv7Lv2cP1AZY8zlEEbMV/6DvInJujxGwcqZjdrDIIQxCefIDg/NWooKyG1JzHZOPWKCGpOp9XICrhsH9x8FDSI16iNoQFIlJX7J+wO4Z3j7i6O4L4xVWO0qYMWfGeePT3kVs9NO314uDTlOVcWcGvJrmM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
