travis:
  secure:
    BINSTAR_TOKEN: AIKHhph3RozPLl4kVh7/A8u93YewElu3R1vtTEJG7NyGW0FJp6WZrxHNZa04TS/a8NLf9DDct82ZfnD7Uw7yZc1g9AYgJOUb0Rpbp7OQuLszwkh/VHge9DNowwRIOL8NxOJgsclRUMmmmJdGqr1H6Y666YOotyUvRgdYTB8gqriF/S2DdQOoYaE8GQ9D3PnE3RQ2C9yK+F9M64N1/OPOjcgZg0IcGtKDMEtsVMW5oFj6LDUDIHmTMlbwkASfL/x++Jbpsm3hgTSyIHp301l0EH61D7LbCBgIE0pyr2u+LDn/q3oO3zEHCSgOuTVOb8bMkO/3NREaY0WWSNaSMhuWb6J+AY9b+gP79vdAun7nMXfOv2mksdfbg/eE+ULIdykoTPaNTGT0fNmkCmQklT30StuhlgVvk2ijmtzoussx99P0U5FlnL6hQcvIeUIJOKrjIiqAURg/ZhCecxIjMaRRBgfdYoVf98U95IHbXKBOt4IRgrcmi2qMkB+Rdmt81+iAZ9ovOQgUKLs+5OZ3kRgWnoQY8d/fXjzhXYN1zN3Zkf6Z8IdnjnPUEYRBwpOPcj6fI88fHecvBd7mH+a7+qpoO64jl6lfVbhK+562LAutg7hgjrBQ/Rw5kTSLJnNkGsMyeOfdndS4ghWn8ZCP5Mdgvh9GfHiSkIlqpLmDfVJXHOs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
